name: Build zoxide for Debian

on:
  workflow_dispatch:
    inputs:
      zoxide_version:
        description: The version of zoxide to build.
        type: string
        required: true
      build_version:
        description: The build version.
        type: string
        required: true

permissions:
  contents: write

jobs:
  build-zoxide:
    name: Build
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout zoxide-debian
        uses: actions/checkout@v4

      - name: Build zoxide
        run: ./build.sh ${{ inputs.zoxide_version }} ${{ inputs.build_version }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: zoxide_*.deb


  release-zoxide:
    name: (Draft-)Release zoxide for Debian
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-zoxide
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Publish Release Draft
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: zoxide_*.deb
          name: ${{ inputs.zoxide_version }}+${{ inputs.build_version }}
          tag_name: ${{ env.RELEASE_TAG }}
          fail_on_unmatched_files: true
